[[osmium]]
arch = "aarch64"
git-tree-sha1 = "7a754be0113c4e8db05e5485a0448f1cdacf2813"
os = "macos"

    [[osmium.download]]
    sha256 = "b44b5955da7adc74c48b9158c8d905c50edcefe19ecaa34c9fcab670c50fbc21"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.16.0+0/osmium.v1.16.0.aarch64-apple-darwin.tar.gz"
[[osmium]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f5fc52513035d0d58517e445d96b1c97f76c9c89"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "efeada0af4f1763f50f29466f497d1c61976334914ec22e78604d2a1517fc6d1"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.16.0+0/osmium.v1.16.0.aarch64-linux-gnu-cxx03.tar.gz"
[[osmium]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c4ab451efcff135773439f59616041bdd237b3ce"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "0cc436beeb851956b1ba25f71fc891d78457edc56b944998e703fb1e19aa9efb"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.16.0+0/osmium.v1.16.0.aarch64-linux-gnu-cxx11.tar.gz"
[[osmium]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6c4d0e35b5e9e98e103c34a17251243a2186bc35"
libc = "musl"
os = "linux"

    [[osmium.download]]
    sha256 = "23f5b3670af398d4a7bca17417c1c10269ca03de1f0c3d226a14694fc1f262d7"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.16.0+0/osmium.v1.16.0.aarch64-linux-musl-cxx03.tar.gz"
[[osmium]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1116ecd3cde3c5e59b4664e6466a0aa8fa1f3e59"
libc = "musl"
os = "linux"

    [[osmium.download]]
    sha256 = "e64d822ad80faf85dd9d263f84ebeb60b5387966fd297fc67639f51c2008592b"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.16.0+0/osmium.v1.16.0.aarch64-linux-musl-cxx11.tar.gz"
[[osmium]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d08d5ba2cc9ca3c123b5b262996e7649d0893a40"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "13474e3beef4855f083449e07f4bf72b8ae5967b9b1e55a8476ac206098536be"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.16.0+0/osmium.v1.16.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[osmium]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4c9e532518065299be1bbf1649233c244fca8cd5"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "d707cbc5f48657a06d3aa87d16496c580e71ffdc0e0ace5093b87077501a03e9"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.16.0+0/osmium.v1.16.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[osmium]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7b99cff08ab082a7ee9f5ce9637f908a2fb61d10"
libc = "musl"
os = "linux"

    [[osmium.download]]
    sha256 = "c754eab99104ae3627f83d622d4f1da0bbbb4d6f86866780228a742d565dc4db"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.16.0+0/osmium.v1.16.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[osmium]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f5de51a81f973a743ff129e9cd05fb7194eb615"
libc = "musl"
os = "linux"

    [[osmium.download]]
    sha256 = "1ef68093c6b38f5841de34e23b66782cdc10c75a66b636495fe52c336b225773"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.16.0+0/osmium.v1.16.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[osmium]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c95fc4ebd94bad44555d6265becd7a84dfe673e6"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "94feae78fb036ae5c912e0d187203acb99c8ef35ad82495ccda851ecec37595d"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.16.0+0/osmium.v1.16.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[osmium]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "171d812094804ad568542de1d5c2f3b1cb81d9e2"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "f1e610e9e7df8d477cf4f50468bc535e4e7dd51008ae6a1f9ef3956e06533bdb"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.16.0+0/osmium.v1.16.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[osmium]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "af5c51a369ea688e379682a73e91bb5d7c005ead"
libc = "musl"
os = "linux"

    [[osmium.download]]
    sha256 = "e16057f5748a16107079fa343bd0a4ce5b2d0b1d27b385e0d80e27f9045c235f"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.16.0+0/osmium.v1.16.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[osmium]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c73838a570422211ee3ca7ae3f06b269f94c7ee9"
libc = "musl"
os = "linux"

    [[osmium.download]]
    sha256 = "8cbf621ec59e08ebe6dfef95ac7e161392e57350d37d3b7a7ac2f9695a8348b6"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.16.0+0/osmium.v1.16.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[osmium]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "57f99681611fe2842655c5eee91f131f314e0e29"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "d8f49fedd5421c74a78a494976d62ac35d4e147bb49e89c8eee98331e154d919"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.16.0+0/osmium.v1.16.0.i686-linux-gnu-cxx03.tar.gz"
[[osmium]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b78531adacec5883ea31e2a990b9bbb66f639e26"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "91e34080c20ebc42a972373e92786fdafb45b0eba33ba2d5e9870226d3f7cd03"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.16.0+0/osmium.v1.16.0.i686-linux-gnu-cxx11.tar.gz"
[[osmium]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3d921ff0ab2a07d791aefe0e5ee55d1c9b8ea43b"
libc = "musl"
os = "linux"

    [[osmium.download]]
    sha256 = "47f981d56ebffcd7160be41282c886571d2f0652765b5e5aa3cc1d0a372c2df0"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.16.0+0/osmium.v1.16.0.i686-linux-musl-cxx03.tar.gz"
[[osmium]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "05ea15d3142aff2ec8ad8e184cb2cd9d3985c2f0"
libc = "musl"
os = "linux"

    [[osmium.download]]
    sha256 = "23de60159d84140c9be8964817d9ca4cf8faf2447663ed7c8d6063e9301e82a1"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.16.0+0/osmium.v1.16.0.i686-linux-musl-cxx11.tar.gz"
[[osmium]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ab331a3a0ced13f9219677dcfa35fd871393e7d8"
os = "windows"

    [[osmium.download]]
    sha256 = "67e80c657671593d20f256e6f6cfb6efa2887ad1254ff5492d90d8963234543b"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.16.0+0/osmium.v1.16.0.i686-w64-mingw32-cxx03.tar.gz"
[[osmium]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "476739f99ed40542498aecc0560ffefa0c6b329a"
os = "windows"

    [[osmium.download]]
    sha256 = "a61d3b16c32de4e1eeb48c0beab63a29aa300ed8654bf682a4836629142173de"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.16.0+0/osmium.v1.16.0.i686-w64-mingw32-cxx11.tar.gz"
[[osmium]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "df141d4f4e3ef5b99279a5c8d5f97aa6ee61c217"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "ddc420c263086a8cb8ec0f04ff8295acca3fc37630e48472d432561a8c3ae099"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.16.0+0/osmium.v1.16.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[osmium]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f9cf1d807e4a85eda182b088f0734651588b7cc"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "62230d457956f63681e195f6ecd98119da60a3454f0a89e7a797340f0bc1c63f"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.16.0+0/osmium.v1.16.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[osmium]]
arch = "x86_64"
git-tree-sha1 = "037ebc3cf4788b1931bb0464c935bd1fdf825c77"
os = "macos"

    [[osmium.download]]
    sha256 = "26fd41cfd4a4ad935681f482e169a11dad7d967eddfdf97ff83ff652fe68d46f"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.16.0+0/osmium.v1.16.0.x86_64-apple-darwin.tar.gz"
[[osmium]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "183e8bbe9b215fa9ca7af6ce6a0d126f1cdbab19"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "f305ee03dde1fb6ed72e41cef07bdae7e24b0e9989e229e43e2443ab59446cbc"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.16.0+0/osmium.v1.16.0.x86_64-linux-gnu-cxx03.tar.gz"
[[osmium]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d3187db470ba1e41a3b29271d924f916626df1f3"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "a06932ac5b8b0eb4aaeb5dace74fcce947f91ba90c6ca4c8b4e81fd2b8f425d7"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.16.0+0/osmium.v1.16.0.x86_64-linux-gnu-cxx11.tar.gz"
[[osmium]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d03dcbe8688f28db11656d8db35c66bde748f439"
libc = "musl"
os = "linux"

    [[osmium.download]]
    sha256 = "8dbae07d5dd931be4387f98f26fe9c3b26ab7006a53d1a864758cb5ce761ade9"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.16.0+0/osmium.v1.16.0.x86_64-linux-musl-cxx03.tar.gz"
[[osmium]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c7c6c96d309648e4c6197477384c5c9180cd5f7"
libc = "musl"
os = "linux"

    [[osmium.download]]
    sha256 = "e48c723ec80ad1028672fc078feddb7e9ceea679a170a336a2d40ef0481e0220"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.16.0+0/osmium.v1.16.0.x86_64-linux-musl-cxx11.tar.gz"
[[osmium]]
arch = "x86_64"
git-tree-sha1 = "dca08e2cd095a21f1cf9281ac5e38342178bf2cd"
os = "freebsd"

    [[osmium.download]]
    sha256 = "caa50cc1ea1c527028c74900bf03c9a53b328a1ab1cfda4e8d583bb0ba42ec55"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.16.0+0/osmium.v1.16.0.x86_64-unknown-freebsd.tar.gz"
[[osmium]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e31d0b1f54242da2dbe9942137a5ca9cdc717f9c"
os = "windows"

    [[osmium.download]]
    sha256 = "e0cbc572aadf703ca696aae9da66fd66c8249116c1ffe644557f0629437e378e"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.16.0+0/osmium.v1.16.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[osmium]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ecf1bf586cf4560609c96d9a0fc6f3cd972efecf"
os = "windows"

    [[osmium.download]]
    sha256 = "22a0cb970556a8551bfa38a4294f130b7e6e5d7105596a3454a814428a166c34"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.16.0+0/osmium.v1.16.0.x86_64-w64-mingw32-cxx11.tar.gz"
