[[osmium]]
arch = "aarch64"
git-tree-sha1 = "a84b4ad4424382fd634dbd990bf8dd06f6c3db0b"
os = "macos"

    [[osmium.download]]
    sha256 = "9111d1bf118c65c6adb3ebd45aa3ec227caa6c01f398ff3926e65cd6633f05a9"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.15.0+0/osmium.v1.15.0.aarch64-apple-darwin.tar.gz"
[[osmium]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "56f387db1474f26fd570ddc9a632426c7958f21a"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "324ce3f0c1615a88e38b40b237bd108391560f95130e4c5c48cdb7ab35b9c32c"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.15.0+0/osmium.v1.15.0.aarch64-linux-gnu-cxx03.tar.gz"
[[osmium]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b98d87c5e1bb84b2b52b27245b6e4222b0bbf3d6"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "07342afddc16656dc51e8847446fd2a47f111e8756908467d965a2e7694cc3a3"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.15.0+0/osmium.v1.15.0.aarch64-linux-gnu-cxx11.tar.gz"
[[osmium]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "32f7de411b905d6e17a5c0d32fad7dce2219b8fd"
libc = "musl"
os = "linux"

    [[osmium.download]]
    sha256 = "3ced25d2f5126da0f063814fabf92d49e647539cd837d7881a2727e244994877"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.15.0+0/osmium.v1.15.0.aarch64-linux-musl-cxx03.tar.gz"
[[osmium]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c8fc6c417f9ea49dda0c8234634eaea0e45d69cb"
libc = "musl"
os = "linux"

    [[osmium.download]]
    sha256 = "33704862de5d77f1f6c00c4884cf2508db53fa2418965537caa4b3e6bea31ad3"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.15.0+0/osmium.v1.15.0.aarch64-linux-musl-cxx11.tar.gz"
[[osmium]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "274ebd3ce177d53b244f786dd8740f5d03307647"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "1c93e7b04ed9c0c87eeebfa5c0692e931febf6434483cd499e93c6615e37b17d"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.15.0+0/osmium.v1.15.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[osmium]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7b1dc3000637646ab77f47060a89785df7877026"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "ad9546e2bcdb0ffcef5d0ddfc36b561f30184f95f358fb28b28130c2c868dd62"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.15.0+0/osmium.v1.15.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[osmium]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f4a30b8f1877739fdf36546cd86db12e746a02cc"
libc = "musl"
os = "linux"

    [[osmium.download]]
    sha256 = "bb435da73d4a788ec11a145c4ab3b3350be395016378b5c3db82d224a6559922"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.15.0+0/osmium.v1.15.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[osmium]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "af5448ecb2cc2b4a78239ba006b59a4e6083796b"
libc = "musl"
os = "linux"

    [[osmium.download]]
    sha256 = "da0a49db7e85bb3e3fde22626ab9b25aea574836f3575909890ebbba3334413d"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.15.0+0/osmium.v1.15.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[osmium]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "57616b0d7d1b12ac04e0b6dbbbeb7ec6cc966088"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "afe534cbeb2dd5db9cc387f053ab0008890cb4fd47ca272e5e32e83e04339965"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.15.0+0/osmium.v1.15.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[osmium]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "369a62be50a12102e59599603519540bb748aa1d"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "c450d24726a428733a29ed783f8c8ec706aa0fe77361bb7955e91e8f20701b5a"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.15.0+0/osmium.v1.15.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[osmium]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8741a992f3c67e258fd9e37aaa35666d4063e0e6"
libc = "musl"
os = "linux"

    [[osmium.download]]
    sha256 = "3d83ba567202e2c43acf5850d5eeff14dbbff4fab3dd0dbefcf47ac68979dd84"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.15.0+0/osmium.v1.15.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[osmium]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2eef7ace7dc0f516b4d0df1fe3dc46a2cd5b34e6"
libc = "musl"
os = "linux"

    [[osmium.download]]
    sha256 = "4a5768ae5b9b5cbd8253345c863e26c9078b3929607af738c4937e8f6765fa04"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.15.0+0/osmium.v1.15.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[osmium]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3c07206921c98fb912ddbeb9329c8600a344e584"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "f82fc8fe4c39b09ffe7d4eb3bd0dee7b739466e8f404a9c6c7178d086c54772c"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.15.0+0/osmium.v1.15.0.i686-linux-gnu-cxx03.tar.gz"
[[osmium]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1984574175643d7cb7660c98c44966fd26ca5e5f"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "6719774dce7a8601129d9b194ea89ca6e05f4a054c19f56348f64259dc2457aa"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.15.0+0/osmium.v1.15.0.i686-linux-gnu-cxx11.tar.gz"
[[osmium]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a8dc18462abfd4a950761139af43941baaf9d3b5"
libc = "musl"
os = "linux"

    [[osmium.download]]
    sha256 = "60b574d4385235078449ad746047333127022e149da5b917df253efee9a64c67"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.15.0+0/osmium.v1.15.0.i686-linux-musl-cxx03.tar.gz"
[[osmium]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12c0f42f8d5e0f7cc7be51315c4914f2b84726bd"
libc = "musl"
os = "linux"

    [[osmium.download]]
    sha256 = "0843522f095f14c01e62a3588daabe3680e58d6a998ef1ac82325c6da62ef290"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.15.0+0/osmium.v1.15.0.i686-linux-musl-cxx11.tar.gz"
[[osmium]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b9689e34fbcc4532002125b65f77d7c1bce91bd0"
os = "windows"

    [[osmium.download]]
    sha256 = "95368b63d4bfa71d3f211bdd0b8a8c89ae28df490a4be3394845c54b7fdefa7c"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.15.0+0/osmium.v1.15.0.i686-w64-mingw32-cxx03.tar.gz"
[[osmium]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d824b13bab18317cd7a19ed567a8a2bd9afa7668"
os = "windows"

    [[osmium.download]]
    sha256 = "e18d9d355ef0dd1dc7adf7a55c7bbdd644cc955db6ac00cda60d7acb06f18c51"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.15.0+0/osmium.v1.15.0.i686-w64-mingw32-cxx11.tar.gz"
[[osmium]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e0cdc4b73d8bddcbe84ba24c2944f1eedc1896ef"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "71d22e2496768821707908ad12be08ce9c04279c9bdfcde6107dfb58c23b6513"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.15.0+0/osmium.v1.15.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[osmium]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2205ab6756088ab3faa887785fc4d390f20e8178"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "cdcc75ed2fbb3280eae2b2e199425689b7e4fac01d01678f6db55092f70442f8"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.15.0+0/osmium.v1.15.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[osmium]]
arch = "x86_64"
git-tree-sha1 = "090d41f6849a243fd32852fbd312684b02e7d624"
os = "macos"

    [[osmium.download]]
    sha256 = "eabf1945a23a85c50c432d55eaf01660691cb2ddc0074f0cb41da00d88e8e899"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.15.0+0/osmium.v1.15.0.x86_64-apple-darwin.tar.gz"
[[osmium]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "79aacf2c2654ba07fcdf89bd4f85730c584f9fb5"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "31f5de568e50b12f9625053f7eb1047ba675f22ca81b857cfb9b45e704337831"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.15.0+0/osmium.v1.15.0.x86_64-linux-gnu-cxx03.tar.gz"
[[osmium]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "832eac01fd692ebf5084daa17ee359128de99bca"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "3fd7b6c940802e28616f7c79b37e0abf427157ade0fd95a154f48d0ec8937c28"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.15.0+0/osmium.v1.15.0.x86_64-linux-gnu-cxx11.tar.gz"
[[osmium]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ec6bb3c3e0550e3a93c56faa7bc66b50cb6df3dd"
libc = "musl"
os = "linux"

    [[osmium.download]]
    sha256 = "e5f387d523701ca4e763de16f3c5689634a5890cbf4d3caacef77557d4d89c09"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.15.0+0/osmium.v1.15.0.x86_64-linux-musl-cxx03.tar.gz"
[[osmium]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9b1ca747a6eff7e7c37a08bd68b999ab34c229e7"
libc = "musl"
os = "linux"

    [[osmium.download]]
    sha256 = "e7a5bb27fc22ab52499ba1db3402e4e44cab4b3b464137fd7670ee65d27afa64"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.15.0+0/osmium.v1.15.0.x86_64-linux-musl-cxx11.tar.gz"
[[osmium]]
arch = "x86_64"
git-tree-sha1 = "ef7e29e84a9d37cce63a29f19456cb1cd8453d7c"
os = "freebsd"

    [[osmium.download]]
    sha256 = "d8a71afe1047dd6183808bca47302715d15427c3149fa44c277de4905c65bbf4"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.15.0+0/osmium.v1.15.0.x86_64-unknown-freebsd.tar.gz"
[[osmium]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7d18af75bfc09c149e490754f3d948e8c9f8323c"
os = "windows"

    [[osmium.download]]
    sha256 = "3c8d889efdad8ea32d7289634f5a87b3dfef312465653d3a9ecc19060afdf942"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.15.0+0/osmium.v1.15.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[osmium]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8aa04e54fa7c84f6b6d000e6fc2475af273e0fed"
os = "windows"

    [[osmium.download]]
    sha256 = "d420d26010092ef8bb47d9d7cb6e6663afe32e7032bd8306de78799ef00b465e"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.15.0+0/osmium.v1.15.0.x86_64-w64-mingw32-cxx11.tar.gz"
