[[osmium]]
arch = "aarch64"
git-tree-sha1 = "075703776654ffa11ad84ad730e1da6683a1f8cf"
os = "macos"

    [[osmium.download]]
    sha256 = "052b8632d0e4601c19295e41bf20979a512583d18cb0984007e46c351bae2971"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.17.0+0/osmium.v1.17.0.aarch64-apple-darwin.tar.gz"
[[osmium]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f68b290873b63eadbf5b384b4f6a78786906c06e"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "422ab345b0a04b81116b9a06927757f916464f3028a63683bc695dbaf313f67f"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.17.0+0/osmium.v1.17.0.aarch64-linux-gnu-cxx03.tar.gz"
[[osmium]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fee178ea28312988bd9face29543763b2b15bfb7"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "5c5f77715f54954a748b9d4f99f573822a88df23f31efdaf1bc067511afb5fbc"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.17.0+0/osmium.v1.17.0.aarch64-linux-gnu-cxx11.tar.gz"
[[osmium]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6badcb1978d33c1c3e6d73a33d704d92da4d2dc1"
libc = "musl"
os = "linux"

    [[osmium.download]]
    sha256 = "58b10f7abfb35c9e06d2527cc05908c506d5157b5f8178a398b167d17ad50fcb"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.17.0+0/osmium.v1.17.0.aarch64-linux-musl-cxx03.tar.gz"
[[osmium]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e07ada0a86c3c44a966fc00121f8e8f37c51103c"
libc = "musl"
os = "linux"

    [[osmium.download]]
    sha256 = "d563dce269cb13175443ae13f75121c29ffb6478690155da5992e812d3656424"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.17.0+0/osmium.v1.17.0.aarch64-linux-musl-cxx11.tar.gz"
[[osmium]]
arch = "aarch64"
git-tree-sha1 = "63144eebac77e04aa2ace21a5d4d9de56ad5229e"
os = "freebsd"

    [[osmium.download]]
    sha256 = "9d17b68aea6c4265568b898b150d12638aa3a848ffafb8e41105c19a78b14d3f"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.17.0+0/osmium.v1.17.0.aarch64-unknown-freebsd.tar.gz"
[[osmium]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9f61bac43937ec7c159a8ea7486f2ed690cdf847"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "885472268a9dc707780c24bcb53f80ed4f1ae6f46dc37c5b5c7ccfc51fe19ae5"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.17.0+0/osmium.v1.17.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[osmium]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f3a32cebef683fdadffd3744fbb977bea82336dd"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "5f86fedf84d28bfad29a938051a7c75c629dd152ecf4048ec5006106c9554123"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.17.0+0/osmium.v1.17.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[osmium]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1147f2b9d901a8ac22a69653d7896d6af5e1c815"
libc = "musl"
os = "linux"

    [[osmium.download]]
    sha256 = "a1fbe59935722b613e66b74dd8fba9410cfee2e66e8189cb49f7ea979157b6ac"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.17.0+0/osmium.v1.17.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[osmium]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d0fe63885927faf2b7204873093e473f7f9e8f6"
libc = "musl"
os = "linux"

    [[osmium.download]]
    sha256 = "62eeb0402a44fdc8062f2db8bfeefad4278a6fde8ea95d7ede631386bc6f3d3b"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.17.0+0/osmium.v1.17.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[osmium]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c62d937fb48038b904cce45a9450ff9eb6e675be"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "b40ab7e94b4079063fd0b04c70a342d3ab85e04fe9a18be2e358b3bf7a6af437"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.17.0+0/osmium.v1.17.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[osmium]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c3da8f74a2720c9ea9f1bdfbd0626c5a063011b5"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "44c17daca7312e4d31a209f737d1a2bfd399690b73dc8dfa8bb4f4385ebeb11b"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.17.0+0/osmium.v1.17.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[osmium]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6de82d81303aaa4bcff82c54666aa6d65a7be980"
libc = "musl"
os = "linux"

    [[osmium.download]]
    sha256 = "bf4e0c79f2f005a4680a7875b6e2d66e9d8ceed194e52cd453a7d6179c32ed70"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.17.0+0/osmium.v1.17.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[osmium]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4c13a4ddf6b567468439ec4768a96665bce348ad"
libc = "musl"
os = "linux"

    [[osmium.download]]
    sha256 = "9911da1dd349b88b8fc542d6ee247602de4eae8a432bec5514ab9b9d16d617dd"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.17.0+0/osmium.v1.17.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[osmium]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "07c6ceb2885320e08651c6dea356d0c289acef9f"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "46b61ba04f92d38d81806f8738705463e8dffccaf5847b1b29cc59d12b7f0808"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.17.0+0/osmium.v1.17.0.i686-linux-gnu-cxx03.tar.gz"
[[osmium]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "109d1164d782686bd9ae2dd96069241c6dce7bbe"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "a1531c90df24936f2861433e942c1e9a4cc1e83ce048fbfdf313ec1a5b0a05b2"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.17.0+0/osmium.v1.17.0.i686-linux-gnu-cxx11.tar.gz"
[[osmium]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ee36f265d99b94c30eb1aa5e4fb5b3030396a51f"
libc = "musl"
os = "linux"

    [[osmium.download]]
    sha256 = "cd65a1203024c8882394296efcfde8420b0cf58adf148c2d54ed0da1b5f28b97"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.17.0+0/osmium.v1.17.0.i686-linux-musl-cxx03.tar.gz"
[[osmium]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef7a11ab79dfa9c0151e5f2f11803807be80039a"
libc = "musl"
os = "linux"

    [[osmium.download]]
    sha256 = "d31eb72bac35620701a6dd23da3db3315361e041e2867c8f04d867f461a197fd"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.17.0+0/osmium.v1.17.0.i686-linux-musl-cxx11.tar.gz"
[[osmium]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "33b43f0b9ab3fabcd13168ad6d052e414c0db60d"
os = "windows"

    [[osmium.download]]
    sha256 = "7f24c2610d48402c457d7051ca26d16d1230b56928615a18f291373b61ebc00c"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.17.0+0/osmium.v1.17.0.i686-w64-mingw32-cxx03.tar.gz"
[[osmium]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b407e52560d1de2a9f4ec0fcfdba1e14abe7784c"
os = "windows"

    [[osmium.download]]
    sha256 = "5dc7b99e6733d4e474c179a750e0ba6a4ac48e3c57d48d1bc00aadec3b628a38"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.17.0+0/osmium.v1.17.0.i686-w64-mingw32-cxx11.tar.gz"
[[osmium]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "50dc8b194c9782ea9bb395243bfb84a972cc113a"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "270f6e6051a7e2b47e86fce0ecefcfb727484e27bc4bb5ebf40ef9e11278fb40"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.17.0+0/osmium.v1.17.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[osmium]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a620349752fb3db75f52f778b6f73436b89cd73d"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "a3914f062864951079a53f22ca19b6fe2f883e7e1cca942cc6e7bf79d9254f20"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.17.0+0/osmium.v1.17.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[osmium]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "07d576e427ae33643391dc40c6bcad351f368b2b"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "b1d648ce2b518f54a80e563fcd1fb8aa22a7f4ad0a93e43dc271613afe7297af"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.17.0+0/osmium.v1.17.0.riscv64-linux-gnu-cxx03.tar.gz"
[[osmium]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a7424232d44bb739d4a6e81655d96a9a6188895f"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "3cc4f2e71415b8664ee78e32e6b89184b38a8003cbe60c1395faf6dfcec1166b"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.17.0+0/osmium.v1.17.0.riscv64-linux-gnu-cxx11.tar.gz"
[[osmium]]
arch = "x86_64"
git-tree-sha1 = "3618b103e29059176063ea55a7acd041e54c9a18"
os = "macos"

    [[osmium.download]]
    sha256 = "edb383ee21db67d220f142d211076303eda6587e9d38372fda76b90b09201be6"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.17.0+0/osmium.v1.17.0.x86_64-apple-darwin.tar.gz"
[[osmium]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eaee1185c8f03d0bbd0dc405d4689bb7c1c3d95c"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "47caf34bf061fcf17b08a26c8810138bed8903c283a5c1c3ee56647829d38e2c"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.17.0+0/osmium.v1.17.0.x86_64-linux-gnu-cxx03.tar.gz"
[[osmium]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e5b01ac82b4da124ea7f39ade783cafeadf8a172"
libc = "glibc"
os = "linux"

    [[osmium.download]]
    sha256 = "8a6cc606605726191b8e412637fac1cb4be7e676b97b85b1f7b424232be756de"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.17.0+0/osmium.v1.17.0.x86_64-linux-gnu-cxx11.tar.gz"
[[osmium]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6be36a6b89a1248c390b60558529ad4c9952aa7f"
libc = "musl"
os = "linux"

    [[osmium.download]]
    sha256 = "be572b70a10e21a10d719d9578d7f9e78359e966d2a619ecc74f01c6e015fd1a"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.17.0+0/osmium.v1.17.0.x86_64-linux-musl-cxx03.tar.gz"
[[osmium]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c076ab6b44f6150af14d1f6b1a2596a76bf38091"
libc = "musl"
os = "linux"

    [[osmium.download]]
    sha256 = "13a2099bc0ee1b57d23802ebf78963dd118c54672eae0dabf6524f65c91f9823"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.17.0+0/osmium.v1.17.0.x86_64-linux-musl-cxx11.tar.gz"
[[osmium]]
arch = "x86_64"
git-tree-sha1 = "7334389f11cfea3d0433b21c6a746c85335d3c8b"
os = "freebsd"

    [[osmium.download]]
    sha256 = "8e82730c1dbb65bd7695a9a39b983ecbf36150778d9526ed359d4a298dd7a2ea"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.17.0+0/osmium.v1.17.0.x86_64-unknown-freebsd.tar.gz"
[[osmium]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "77bc48fb75fd4576058a692ea7d6931b91675502"
os = "windows"

    [[osmium.download]]
    sha256 = "724ad671955d2010a8790566715b0cd7ad6b92005dccb05ecb3bb2dfa92289aa"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.17.0+0/osmium.v1.17.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[osmium]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6d10d8442f7de2640104f50cf7c15cc193c20d2b"
os = "windows"

    [[osmium.download]]
    sha256 = "b0a37394cb7ab1b8e63430de63d7a47f4430bb243dae1b8801973ea3b4e64409"
    url = "https://github.com/JuliaBinaryWrappers/osmium_jll.jl/releases/download/osmium-v1.17.0+0/osmium.v1.17.0.x86_64-w64-mingw32-cxx11.tar.gz"
